// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolApp.Data;

#nullable disable

namespace SchoolApp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("1874d51f-29bc-4669-8f9d-938eaa55e4dd"),
                            RoleId = new Guid("bc1bfaec-7297-48f0-a649-f290de46ad74")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SchoolApp.Data.Models.Absence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Absence identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Date of creation");

                    b.Property<bool>("IsExcused")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Absence status");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasComment("Student identifier");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasComment("Subject identifier");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Absences", t =>
                        {
                            t.HasComment("Absences table");
                        });
                });

            modelBuilder.Entity("SchoolApp.Data.Models.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Album identifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Album description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Album title");

                    b.HasKey("Id");

                    b.ToTable("Albums", t =>
                        {
                            t.HasComment("Albums table");
                        });
                });

            modelBuilder.Entity("SchoolApp.Data.Models.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Announcement identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Announcement content");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2")
                        .HasComment("Announcement publication date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Announcement title");

                    b.HasKey("Id");

                    b.ToTable("Announcements", t =>
                        {
                            t.HasComment("Announcements table");
                        });
                });

            modelBuilder.Entity("SchoolApp.Data.Models.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bc1bfaec-7297-48f0-a649-f290de46ad74"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("951a0b30-2bcb-4e61-b0fa-d90512119130"),
                            Name = "Parent",
                            NormalizedName = "PARENT"
                        },
                        new
                        {
                            Id = new Guid("167b9fd4-2252-4d5f-9b5d-867599a3e746"),
                            Name = "Teacher",
                            NormalizedName = "TEACHER"
                        });
                });

            modelBuilder.Entity("SchoolApp.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("39d7bb6d-eb8a-40fc-be00-9c5296a2717c"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "30699498-56e0-4d62-ae26-4f4c5d2fd1cc",
                            Email = "Stefan@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "STEFAN@GMAIL.COM",
                            NormalizedUserName = "STEFAN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEL07dWmxTsbCzAmBwlhIP1hQRwp37xkWYOUxsp8ZGgXqCzjTxu7d6UUCX/y8nUweQQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4C7A51C6-35DF-4840-AA09-7764F6F84377",
                            TwoFactorEnabled = false,
                            UserName = "Stefan@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("79eb351b-ed32-4309-9234-88db8555cd3d"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a8a45cec-cf96-4e8e-94db-f42f6623b8b0",
                            Email = "Margarita@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "MARGARITA@GMAIL.COM",
                            NormalizedUserName = "MARGARITA@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEoNYKqfDn1wZC6rqHNda/7ghcmIqhVjEdLL7acqohp+y5AKSnroNEM1Pqfy5OZRUg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "266849B9-DC84-431D-B8D0-4286D5C2A52B",
                            TwoFactorEnabled = false,
                            UserName = "Margarita@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("e4c5fd5f-c02a-474b-8f51-d4a543f361d3"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8744f9ed-272a-43b6-8ae4-4279a58bc1f7",
                            Email = "Maria@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "MARIA@GMAIL.COM",
                            NormalizedUserName = "MARIA@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEG+UQcUcv4tNmfAznZrU29qG7P1NMinIMdOQwkjtt2gbxjc6irW2kvf39CUZwUdiqQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "09779772-07A4-40B9-9F92-1796E8D09544",
                            TwoFactorEnabled = false,
                            UserName = "Maria@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("d040cb3e-ae29-4045-943c-4030a4249476"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5f397ccc-8af7-430d-9cdd-e5b985d747ea",
                            Email = "Ani@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "ANI@GMAIL.COM",
                            NormalizedUserName = "ANI@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEF0uA3J/BVaYRBmQQSUd2biB8HHGqdD4xltdMlsLQ4goY4G1fZvOdVTpzm8sc+qP2w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "93DDDC56-76F7-4591-A973-73BC8A9E6D0D",
                            TwoFactorEnabled = false,
                            UserName = "Ani@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("1874d51f-29bc-4669-8f9d-938eaa55e4dd"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "21f80dc9-9c2e-4593-a3f1-02327e5989fd",
                            Email = "Tsveti@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "TSVETI@GMAIL.COM",
                            NormalizedUserName = "TSVETI@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBltTZfeYXbEPnxkfqtz9f0SOzIo3EBIVlKb1M9fx8j9Ma4eaofuuc3C0KhK5w0dsQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "CA8633AD-9E8A-48F8-BB0C-F23E4E95E792",
                            TwoFactorEnabled = false,
                            UserName = "Tsveti@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("eaad8ef4-d0c4-4cee-bbf0-e1f8e43a6d99"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7a10df65-743d-4e47-a907-8f03b4961da5",
                            Email = "Emilia@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "EMILIA@GMAIL.COM",
                            NormalizedUserName = "EMILIA@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELIe4YWQX0+M9NjywA2gCLCdcNlDQ4MFHKRNYhFMlteR6TGMGuiOBOeG16CNSnxkiQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "14B6E0BA-1E80-4117-9C46-94BD111C190F",
                            TwoFactorEnabled = false,
                            UserName = "Emilia@gmail.com"
                        });
                });

            modelBuilder.Entity("SchoolApp.Data.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Class identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GradeLevel")
                        .HasColumnType("int")
                        .HasComment("Grade level");

                    b.Property<int>("SectionId")
                        .HasColumnType("int")
                        .HasComment("Section identifier");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Classes", t =>
                        {
                            t.HasComment("Classes table");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GradeLevel = 5,
                            SectionId = 1
                        },
                        new
                        {
                            Id = 2,
                            GradeLevel = 5,
                            SectionId = 2
                        },
                        new
                        {
                            Id = 3,
                            GradeLevel = 5,
                            SectionId = 3
                        },
                        new
                        {
                            Id = 4,
                            GradeLevel = 6,
                            SectionId = 1
                        },
                        new
                        {
                            Id = 5,
                            GradeLevel = 6,
                            SectionId = 2
                        },
                        new
                        {
                            Id = 6,
                            GradeLevel = 6,
                            SectionId = 3
                        });
                });

            modelBuilder.Entity("SchoolApp.Data.Models.GalleryImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Image identifier");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Album identifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2083)
                        .HasColumnType("nvarchar(2083)")
                        .HasComment("Image URL");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("GalleryImages", t =>
                        {
                            t.HasComment("Gallery images table");
                        });
                });

            modelBuilder.Entity("SchoolApp.Data.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Grade identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Date of creation");

                    b.Property<int>("GradeType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasComment("Grade type");

                    b.Property<int>("GradeValue")
                        .HasColumnType("int")
                        .HasComment("Grade value");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasComment("Student identifier");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasComment("Subject identifier");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Teacher identifier");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Grades", t =>
                        {
                            t.HasComment("Grades table");
                        });
                });

            modelBuilder.Entity("SchoolApp.Data.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("News identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int")
                        .HasComment("News category");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("News content");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2083)
                        .HasColumnType("nvarchar(2083)")
                        .HasComment("Image URL");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Archive status");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2")
                        .HasComment("Publication date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("News title");

                    b.HasKey("Id");

                    b.ToTable("News", t =>
                        {
                            t.HasComment("News table");
                        });
                });

            modelBuilder.Entity("SchoolApp.Data.Models.Remark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Remark identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Date of creation");

                    b.Property<string>("RemarkText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("Remark text");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasComment("Student identifier");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasComment("Subject identifier");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Teacher identifier");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Remarks", t =>
                        {
                            t.HasComment("Remarks table");
                        });
                });

            modelBuilder.Entity("SchoolApp.Data.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Section identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasComment("Section name");

                    b.HasKey("Id");

                    b.ToTable("Sections", t =>
                        {
                            t.HasComment("Sections table");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "А"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Б"
                        },
                        new
                        {
                            Id = 3,
                            Name = "В"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Г"
                        });
                });

            modelBuilder.Entity("SchoolApp.Data.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Student identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Application user identifier");

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasComment("Class identifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Student first name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Student last name");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Student middle name");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ClassId");

                    b.ToTable("Students", t =>
                        {
                            t.HasComment("Students table");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationUserId = new Guid("39d7bb6d-eb8a-40fc-be00-9c5296a2717c"),
                            ClassId = 1,
                            FirstName = "Иван",
                            LastName = "Иванов",
                            MiddleName = "Неделинов"
                        },
                        new
                        {
                            Id = 2,
                            ApplicationUserId = new Guid("39d7bb6d-eb8a-40fc-be00-9c5296a2717c"),
                            ClassId = 1,
                            FirstName = "Мария",
                            LastName = "Петрова",
                            MiddleName = "Викторова"
                        },
                        new
                        {
                            Id = 3,
                            ApplicationUserId = new Guid("39d7bb6d-eb8a-40fc-be00-9c5296a2717c"),
                            ClassId = 1,
                            FirstName = "Георги",
                            LastName = "Димитров",
                            MiddleName = "Петрунов"
                        },
                        new
                        {
                            Id = 4,
                            ApplicationUserId = new Guid("39d7bb6d-eb8a-40fc-be00-9c5296a2717c"),
                            ClassId = 2,
                            FirstName = "Елена",
                            LastName = "Станкова",
                            MiddleName = "Георгиева"
                        },
                        new
                        {
                            Id = 5,
                            ApplicationUserId = new Guid("39d7bb6d-eb8a-40fc-be00-9c5296a2717c"),
                            ClassId = 2,
                            FirstName = "Петра",
                            LastName = "Стайкова",
                            MiddleName = "Петрунова"
                        },
                        new
                        {
                            Id = 6,
                            ApplicationUserId = new Guid("39d7bb6d-eb8a-40fc-be00-9c5296a2717c"),
                            ClassId = 2,
                            FirstName = "Георги",
                            LastName = "Петров",
                            MiddleName = "Иванов"
                        },
                        new
                        {
                            Id = 7,
                            ApplicationUserId = new Guid("39d7bb6d-eb8a-40fc-be00-9c5296a2717c"),
                            ClassId = 3,
                            FirstName = "Мария",
                            LastName = "Петрова",
                            MiddleName = "Георгиева"
                        },
                        new
                        {
                            Id = 8,
                            ApplicationUserId = new Guid("39d7bb6d-eb8a-40fc-be00-9c5296a2717c"),
                            ClassId = 3,
                            FirstName = "Иван",
                            LastName = "Иванов",
                            MiddleName = "Стефанов"
                        },
                        new
                        {
                            Id = 9,
                            ApplicationUserId = new Guid("39d7bb6d-eb8a-40fc-be00-9c5296a2717c"),
                            ClassId = 3,
                            FirstName = "Елена",
                            LastName = "Василева",
                            MiddleName = "Николова"
                        },
                        new
                        {
                            Id = 10,
                            ApplicationUserId = new Guid("39d7bb6d-eb8a-40fc-be00-9c5296a2717c"),
                            ClassId = 4,
                            FirstName = "Никола",
                            LastName = "Димитров",
                            MiddleName = "Петров"
                        },
                        new
                        {
                            Id = 11,
                            ApplicationUserId = new Guid("39d7bb6d-eb8a-40fc-be00-9c5296a2717c"),
                            ClassId = 4,
                            FirstName = "Петър",
                            LastName = "Димитров",
                            MiddleName = "Георгиев"
                        },
                        new
                        {
                            Id = 12,
                            ApplicationUserId = new Guid("39d7bb6d-eb8a-40fc-be00-9c5296a2717c"),
                            ClassId = 4,
                            FirstName = "Даниела",
                            LastName = "Маринова",
                            MiddleName = "Иванова"
                        },
                        new
                        {
                            Id = 13,
                            ApplicationUserId = new Guid("39d7bb6d-eb8a-40fc-be00-9c5296a2717c"),
                            ClassId = 5,
                            FirstName = "Александър",
                            LastName = "Стоянов",
                            MiddleName = "Николов"
                        },
                        new
                        {
                            Id = 14,
                            ApplicationUserId = new Guid("39d7bb6d-eb8a-40fc-be00-9c5296a2717c"),
                            ClassId = 5,
                            FirstName = "Калина",
                            LastName = "Димитрова",
                            MiddleName = "Петкова"
                        },
                        new
                        {
                            Id = 15,
                            ApplicationUserId = new Guid("39d7bb6d-eb8a-40fc-be00-9c5296a2717c"),
                            ClassId = 5,
                            FirstName = "Радослав",
                            LastName = "Петров",
                            MiddleName = "Георгиев"
                        },
                        new
                        {
                            Id = 16,
                            ApplicationUserId = new Guid("39d7bb6d-eb8a-40fc-be00-9c5296a2717c"),
                            ClassId = 6,
                            FirstName = "Борис",
                            LastName = "Караджов",
                            MiddleName = "Стефанов"
                        },
                        new
                        {
                            Id = 17,
                            ApplicationUserId = new Guid("39d7bb6d-eb8a-40fc-be00-9c5296a2717c"),
                            ClassId = 6,
                            FirstName = "Антония",
                            LastName = "Тодорова",
                            MiddleName = "Илиева"
                        },
                        new
                        {
                            Id = 18,
                            ApplicationUserId = new Guid("39d7bb6d-eb8a-40fc-be00-9c5296a2717c"),
                            ClassId = 6,
                            FirstName = "Виктор",
                            LastName = "Колев",
                            MiddleName = "Алексиев"
                        });
                });

            modelBuilder.Entity("SchoolApp.Data.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Subject identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Subject name");

                    b.HasKey("Id");

                    b.ToTable("Subjects", t =>
                        {
                            t.HasComment("Subjects table");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Български език и литература"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Математика"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Физика"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Химия"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Програмиране"
                        },
                        new
                        {
                            Id = 6,
                            Name = "История"
                        });
                });

            modelBuilder.Entity("SchoolApp.Data.Models.SubjectStudent", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasComment("Student identifier");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasComment("Subject identifier");

                    b.HasKey("StudentId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("SubjectsStudents", t =>
                        {
                            t.HasComment("Subject students mapping table");
                        });

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 6
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 6
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 6
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 6
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 6
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 6
                        },
                        new
                        {
                            StudentId = 7,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 7,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 7,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 7,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 7,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 7,
                            SubjectId = 6
                        },
                        new
                        {
                            StudentId = 8,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 8,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 8,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 8,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 8,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 8,
                            SubjectId = 6
                        },
                        new
                        {
                            StudentId = 9,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 9,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 9,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 9,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 9,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 9,
                            SubjectId = 6
                        },
                        new
                        {
                            StudentId = 10,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 10,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 10,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 10,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 10,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 10,
                            SubjectId = 6
                        },
                        new
                        {
                            StudentId = 11,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 11,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 11,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 11,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 11,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 11,
                            SubjectId = 6
                        },
                        new
                        {
                            StudentId = 12,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 12,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 12,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 12,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 12,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 12,
                            SubjectId = 6
                        },
                        new
                        {
                            StudentId = 13,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 13,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 13,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 13,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 13,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 13,
                            SubjectId = 6
                        },
                        new
                        {
                            StudentId = 14,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 14,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 14,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 14,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 14,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 14,
                            SubjectId = 6
                        },
                        new
                        {
                            StudentId = 15,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 15,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 15,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 15,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 15,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 15,
                            SubjectId = 6
                        },
                        new
                        {
                            StudentId = 16,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 16,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 16,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 16,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 16,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 16,
                            SubjectId = 6
                        },
                        new
                        {
                            StudentId = 17,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 17,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 17,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 17,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 17,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 17,
                            SubjectId = 6
                        },
                        new
                        {
                            StudentId = 18,
                            SubjectId = 1
                        },
                        new
                        {
                            StudentId = 18,
                            SubjectId = 2
                        },
                        new
                        {
                            StudentId = 18,
                            SubjectId = 3
                        },
                        new
                        {
                            StudentId = 18,
                            SubjectId = 4
                        },
                        new
                        {
                            StudentId = 18,
                            SubjectId = 5
                        },
                        new
                        {
                            StudentId = 18,
                            SubjectId = 6
                        });
                });

            modelBuilder.Entity("SchoolApp.Data.Models.SubjectTeacher", b =>
                {
                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Teacher identifier");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasComment("Subject identifier");

                    b.HasKey("TeacherId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("SubjectsTeachers", t =>
                        {
                            t.HasComment("Subject teachers mapping table");
                        });
                });

            modelBuilder.Entity("SchoolApp.Data.Models.Teacher", b =>
                {
                    b.Property<Guid>("GuidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Teacher identifier");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Application user identifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Teacher first name");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2083)
                        .HasColumnType("nvarchar(2083)")
                        .HasComment("Image URL");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Job title");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Teacher last name");

                    b.HasKey("GuidId");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasFilter("[ApplicationUserId] IS NOT NULL");

                    b.ToTable("Teachers", t =>
                        {
                            t.HasComment("Teachers table");
                        });

                    b.HasData(
                        new
                        {
                            GuidId = new Guid("3f865489-0188-41e0-ae45-39626a3d9fef"),
                            ApplicationUserId = new Guid("39d7bb6d-eb8a-40fc-be00-9c5296a2717c"),
                            FirstName = "Стефан",
                            ImageUrl = "/img/No_Image.jpg",
                            JobTitle = "Учител",
                            LastName = "Николов"
                        },
                        new
                        {
                            GuidId = new Guid("b37d2ff2-15db-4cd8-9a77-f0052d0b1ab3"),
                            ApplicationUserId = new Guid("79eb351b-ed32-4309-9234-88db8555cd3d"),
                            FirstName = "Маргарита",
                            ImageUrl = "/img/No_Image.jpg",
                            JobTitle = "Учител",
                            LastName = "Йорданова"
                        },
                        new
                        {
                            GuidId = new Guid("01548a2b-68bf-4858-8b9f-61f538fc376a"),
                            ApplicationUserId = new Guid("e4c5fd5f-c02a-474b-8f51-d4a543f361d3"),
                            FirstName = "Мария",
                            ImageUrl = "/img/No_Image.jpg",
                            JobTitle = "Учител",
                            LastName = "Чавдарова"
                        },
                        new
                        {
                            GuidId = new Guid("cf100638-717c-4285-9c8f-25b0b6a8be8d"),
                            ApplicationUserId = new Guid("d040cb3e-ae29-4045-943c-4030a4249476"),
                            FirstName = "Ани",
                            ImageUrl = "/img/No_Image.jpg",
                            JobTitle = "Учител",
                            LastName = "Григорова"
                        },
                        new
                        {
                            GuidId = new Guid("8259e67f-6f7a-4166-b262-20d754b5e2fd"),
                            ApplicationUserId = new Guid("1874d51f-29bc-4669-8f9d-938eaa55e4dd"),
                            FirstName = "Цветелина",
                            ImageUrl = "/img/No_Image.jpg",
                            JobTitle = "Заместник-директор",
                            LastName = "Томова"
                        },
                        new
                        {
                            GuidId = new Guid("47ca7932-75e2-41f7-bc76-c33fdd9033a5"),
                            ApplicationUserId = new Guid("eaad8ef4-d0c4-4cee-bbf0-e1f8e43a6d99"),
                            FirstName = "Емилия",
                            ImageUrl = "/img/No_Image.jpg",
                            JobTitle = "Заместник-директор",
                            LastName = "Истаткова"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("SchoolApp.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SchoolApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SchoolApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("SchoolApp.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SchoolApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolApp.Data.Models.Absence", b =>
                {
                    b.HasOne("SchoolApp.Data.Models.Student", "Student")
                        .WithMany("Absences")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolApp.Data.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolApp.Data.Models.Class", b =>
                {
                    b.HasOne("SchoolApp.Data.Models.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("SchoolApp.Data.Models.GalleryImage", b =>
                {
                    b.HasOne("SchoolApp.Data.Models.Album", "Album")
                        .WithMany("Images")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("SchoolApp.Data.Models.Grade", b =>
                {
                    b.HasOne("SchoolApp.Data.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolApp.Data.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolApp.Data.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolApp.Data.Models.Remark", b =>
                {
                    b.HasOne("SchoolApp.Data.Models.Student", "Student")
                        .WithMany("Remarks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolApp.Data.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolApp.Data.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolApp.Data.Models.Student", b =>
                {
                    b.HasOne("SchoolApp.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolApp.Data.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("SchoolApp.Data.Models.SubjectStudent", b =>
                {
                    b.HasOne("SchoolApp.Data.Models.Student", "Student")
                        .WithMany("SubjectStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolApp.Data.Models.Subject", "Subject")
                        .WithMany("SubjectStudents")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolApp.Data.Models.SubjectTeacher", b =>
                {
                    b.HasOne("SchoolApp.Data.Models.Subject", "Subject")
                        .WithMany("SubjectTeachers")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolApp.Data.Models.Teacher", "Teacher")
                        .WithMany("SubjectTeachers")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolApp.Data.Models.Teacher", b =>
                {
                    b.HasOne("SchoolApp.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("SchoolApp.Data.Models.Teacher", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("SchoolApp.Data.Models.Album", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("SchoolApp.Data.Models.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("SchoolApp.Data.Models.Student", b =>
                {
                    b.Navigation("Absences");

                    b.Navigation("Grades");

                    b.Navigation("Remarks");

                    b.Navigation("SubjectStudents");
                });

            modelBuilder.Entity("SchoolApp.Data.Models.Subject", b =>
                {
                    b.Navigation("SubjectStudents");

                    b.Navigation("SubjectTeachers");
                });

            modelBuilder.Entity("SchoolApp.Data.Models.Teacher", b =>
                {
                    b.Navigation("SubjectTeachers");
                });
#pragma warning restore 612, 618
        }
    }
}
